fake data for seeding db
bencagri/symfony4-ddd pull request #1
Opened 2018-05-18 11:02 UTC by frnxstd

2018-05-18 19:19 UTC, bencagri commented on src/DataFixtures/UserFixtures.php
> +        $user->setEmail($faker->email);
this should be static email.

2018-05-18 19:21 UTC, bencagri requested changes
Could you check the changes?

2018-05-19 07:43 UTC, frnxstd commented on src/DataFixtures/UserFixtures.php
> +        $user->setEmail($faker->email);
I see your point.

2018-05-19 07:45 UTC, bencagri approved these changes
Approved

2018-05-19 07:47 UTC, merged